dbt-fusion 2.0.0-preview.13
   Loading profiles.yml
error: dbt1005: Failed to parse profiles.yml: unknown variant `clickhouse`, expected one of `redshift`, `snowflake`, `postgres`, `bigquery`, `trino`, `datafusion`, `databricks`, `salesforce`
  Finished 'run'  with 1 error in 52ms
New version available 2.0.0-preview.25 (run `dbt system update`)
[0m07:44:32.806178 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a930187a310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a92fe4e7310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a92fe4e7460>]}


============================== 07:44:32.820374 | e2ad2e18-2484-4c7f-8714-37597b0eb491 ==============================
[0m07:44:32.820374 [info ] [MainThread]: Running with dbt=1.8.9
[0m07:44:32.821948 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'write_json': 'True', 'cache_selected_only': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'log_cache_events': 'False', 'log_path': '/workdir/transforms/02_chinook/logs', 'empty': 'False', 'warn_error': 'None', 'debug': 'False', 'printer_width': '80', 'use_experimental_parser': 'False', 'static_parser': 'True', 'profiles_dir': '.', 'introspect': 'True', 'target_path': 'None', 'version_check': 'True', 'send_anonymous_usage_stats': 'True', 'fail_fast': 'False', 'log_format': 'default', 'indirect_selection': 'eager', 'use_colors': 'True', 'invocation_command': 'dbt run --profiles-dir .', 'no_print': 'None', 'quiet': 'False'}
[0m07:44:33.122176 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'e2ad2e18-2484-4c7f-8714-37597b0eb491', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a92fe3e8ee0>]}
[0m07:44:33.214528 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'e2ad2e18-2484-4c7f-8714-37597b0eb491', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a92fe571100>]}
[0m07:44:33.216477 [info ] [MainThread]: Registered adapter: clickhouse=1.8.6
[0m07:44:33.356146 [debug] [MainThread]: checksum: 132857a23e9d07220246854f7763165174ce9b737cfc7867629ace4294e520b1, vars: {}, profile: , target: , version: 1.8.9
[0m07:44:33.581565 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 7 files added, 2 files changed.
[0m07:44:33.582390 [debug] [MainThread]: Partial parsing: added file: ex_02_chinook://models/mart/g2_top_revenue_by_genre_per_country_shi.sql
[0m07:44:33.582942 [debug] [MainThread]: Partial parsing: added file: ex_02_chinook://models/clean/test_simple.sql
[0m07:44:33.583439 [debug] [MainThread]: Partial parsing: added file: ex_02_chinook://models/mart/vw_artist_album_counts_shi.sql
[0m07:44:33.583930 [debug] [MainThread]: Partial parsing: added file: ex_02_chinook://models/clean/stg_chinook__artist.sql
[0m07:44:33.584490 [debug] [MainThread]: Partial parsing: added file: ex_02_chinook://models/mart/dim_album_shi.sql
[0m07:44:33.585009 [debug] [MainThread]: Partial parsing: added file: ex_02_chinook://models/mart/dim_artist_shi.sql
[0m07:44:33.585497 [debug] [MainThread]: Partial parsing: added file: ex_02_chinook://models/clean/stg_chinook__album.sql
[0m07:44:33.586073 [debug] [MainThread]: Partial parsing: updated file: ex_02_chinook://models/sources.yml
[0m07:44:33.586978 [debug] [MainThread]: Partial parsing: updated file: ex_02_chinook://macros/show_raw_tables.sql
[0m07:44:33.948399 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.ex_02_chinook.g2_top_revenue_by_genre_per_country_shi' (models/mart/g2_top_revenue_by_genre_per_country_shi.sql) depends on a source named 'raw.chinook___customer_shi' which was not found
[0m07:44:33.951169 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 1.2582732, "process_in_blocks": "4016", "process_kernel_time": 0.764295, "process_mem_max_rss": "100796", "process_out_blocks": "6608", "process_user_time": 3.897904}
[0m07:44:33.951969 [debug] [MainThread]: Command `dbt run` failed at 07:44:33.951760 after 1.26 seconds
[0m07:44:33.952625 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a930187a310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a92fe93e640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a92fda4e9a0>]}
[0m07:44:33.953273 [debug] [MainThread]: Flushing usage events
[0m07:44:38.971701 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
